/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlarmsRouteImport } from './routes/alarms'
import { Route as ElectricalRouteImport } from './routes/electrical'
import { Route as EquipmentRouteImport } from './routes/equipment'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NetworkRouteImport } from './routes/network'
import { Route as PidRouteImport } from './routes/pid'
import { Route as TanksIndexRouteImport } from './routes/tanks.index'
import { Route as TanksTankIdRouteImport } from './routes/tanks.$tankId'
import { Route as UnitsIndexRouteImport } from './routes/units.index'
import { Route as UnitsUnitIdRouteImport } from './routes/units.$unitId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlarmsRoute = AlarmsRouteImport.update({
  id: '/alarms',
  path: '/alarms',
  getParentRoute: () => rootRouteImport,
} as any)
const ElectricalRoute = ElectricalRouteImport.update({
  id: '/electrical',
  path: '/electrical',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipmentRoute = EquipmentRouteImport.update({
  id: '/equipment',
  path: '/equipment',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkRoute = NetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => rootRouteImport,
} as any)
const PidRoute = PidRouteImport.update({
  id: '/pid',
  path: '/pid',
  getParentRoute: () => rootRouteImport,
} as any)
const TanksIndexRoute = TanksIndexRouteImport.update({
  id: '/tanks/',
  path: '/tanks/',
  getParentRoute: () => rootRouteImport,
} as any)
const TanksTankIdRoute = TanksTankIdRouteImport.update({
  id: '/tanks/$tankId',
  path: '/tanks/$tankId',
  getParentRoute: () => rootRouteImport,
} as any)
const UnitsIndexRoute = UnitsIndexRouteImport.update({
  id: '/units/',
  path: '/units/',
  getParentRoute: () => rootRouteImport,
} as any)
const UnitsUnitIdRoute = UnitsUnitIdRouteImport.update({
  id: '/units/$unitId',
  path: '/units/$unitId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alarms': typeof AlarmsRoute
  '/electrical': typeof ElectricalRoute
  '/equipment': typeof EquipmentRoute
  '/login': typeof LoginRoute
  '/network': typeof NetworkRoute
  '/pid': typeof PidRoute
  '/tanks/$tankId': typeof TanksTankIdRoute
  '/units/$unitId': typeof UnitsUnitIdRoute
  '/tanks/': typeof TanksIndexRoute
  '/units/': typeof UnitsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alarms': typeof AlarmsRoute
  '/electrical': typeof ElectricalRoute
  '/equipment': typeof EquipmentRoute
  '/login': typeof LoginRoute
  '/network': typeof NetworkRoute
  '/pid': typeof PidRoute
  '/tanks/$tankId': typeof TanksTankIdRoute
  '/units/$unitId': typeof UnitsUnitIdRoute
  '/tanks': typeof TanksIndexRoute
  '/units': typeof UnitsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alarms': typeof AlarmsRoute
  '/electrical': typeof ElectricalRoute
  '/equipment': typeof EquipmentRoute
  '/login': typeof LoginRoute
  '/network': typeof NetworkRoute
  '/pid': typeof PidRoute
  '/tanks/$tankId': typeof TanksTankIdRoute
  '/units/$unitId': typeof UnitsUnitIdRoute
  '/tanks/': typeof TanksIndexRoute
  '/units/': typeof UnitsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alarms'
    | '/electrical'
    | '/equipment'
    | '/login'
    | '/network'
    | '/pid'
    | '/tanks/$tankId'
    | '/units/$unitId'
    | '/tanks/'
    | '/units/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alarms'
    | '/electrical'
    | '/equipment'
    | '/login'
    | '/network'
    | '/pid'
    | '/tanks/$tankId'
    | '/units/$unitId'
    | '/tanks'
    | '/units'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/alarms'
    | '/electrical'
    | '/equipment'
    | '/login'
    | '/network'
    | '/pid'
    | '/tanks/$tankId'
    | '/units/$unitId'
    | '/tanks/'
    | '/units/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlarmsRoute: typeof AlarmsRoute
  ElectricalRoute: typeof ElectricalRoute
  EquipmentRoute: typeof EquipmentRoute
  LoginRoute: typeof LoginRoute
  NetworkRoute: typeof NetworkRoute
  PidRoute: typeof PidRoute
  TanksTankIdRoute: typeof TanksTankIdRoute
  UnitsUnitIdRoute: typeof UnitsUnitIdRoute
  TanksIndexRoute: typeof TanksIndexRoute
  UnitsIndexRoute: typeof UnitsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alarms': {
      id: '/alarms'
      path: '/alarms'
      fullPath: '/alarms'
      preLoaderRoute: typeof AlarmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/electrical': {
      id: '/electrical'
      path: '/electrical'
      fullPath: '/electrical'
      preLoaderRoute: typeof ElectricalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipment': {
      id: '/equipment'
      path: '/equipment'
      fullPath: '/equipment'
      preLoaderRoute: typeof EquipmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network': {
      id: '/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof NetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pid': {
      id: '/pid'
      path: '/pid'
      fullPath: '/pid'
      preLoaderRoute: typeof PidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tanks/': {
      id: '/tanks/'
      path: '/tanks'
      fullPath: '/tanks/'
      preLoaderRoute: typeof TanksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tanks/$tankId': {
      id: '/tanks/$tankId'
      path: '/tanks/$tankId'
      fullPath: '/tanks/$tankId'
      preLoaderRoute: typeof TanksTankIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/units/': {
      id: '/units/'
      path: '/units'
      fullPath: '/units/'
      preLoaderRoute: typeof UnitsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/units/$unitId': {
      id: '/units/$unitId'
      path: '/units/$unitId'
      fullPath: '/units/$unitId'
      preLoaderRoute: typeof UnitsUnitIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlarmsRoute: AlarmsRoute,
  ElectricalRoute: ElectricalRoute,
  EquipmentRoute: EquipmentRoute,
  LoginRoute: LoginRoute,
  NetworkRoute: NetworkRoute,
  PidRoute: PidRoute,
  TanksTankIdRoute: TanksTankIdRoute,
  UnitsUnitIdRoute: UnitsUnitIdRoute,
  TanksIndexRoute: TanksIndexRoute,
  UnitsIndexRoute: UnitsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
